autotest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views
from apptest import appviews
from webtest import webviews
from product import proviews
from cmdtest import cmdviews
from set import setviews
from bug import bugviews

urlpatterns = [
    path('admin/', admin.site.urls),
  #  path('test/', views.test),
    path('task_apis/', views.task_apis),
    path('task_apitest/', views.task_apitest),
    path('task_webtest/', views.task_webtest),
    path('task_webtest2/', views.task_webtest2),
    path('task_apptest/', views.task_apptest),
    path('task_apptest2/', views.task_apptest2),
    path('task_cmdtest/', views.task_cmdtest,name='task_cmdtest'),
    path('login/', views.login),
    path('', views.login),
    path('logout/', views.logout),
    path('home/', views.home),
    path ('welcome/', views.welcome),
    path('product_manage/', proviews.product_manage),
    path('productsearch/', proviews.productsearch),
    path('apitest_manage/', views.apitest_manage),
    path('apistep_manage/', views.apistep_manage,name='apistep_manage'),
    path('left/', views.left),
    path('apisearch/', views.apisearch),
    path('apistepsearch/', views.apistepsearch),
    path('apissearch/', views.apissearch),
    path('apis_manage/', views.apis_manage),
    path('periodic_task/', views.periodic_task), 
    path('tasksearch/', views.tasksearch), 
    path('appcase_manage/', appviews.appcase_manage),
    path('appcasestep_manage/', appviews.appcasestep_manage,name='appcasestep_manage'),
    path('appsearch/', appviews.appsearch),
    path('appstepsearch/', appviews.appstepsearch),
    path('webcase_manage/', webviews.webcase_manage),
    path('webcasestep_manage/', webviews.webcasestep_manage,name='webcasestep_manage'),
    path('websearch/', webviews.websearch),
    path('webstepsearch/', webviews.webstepsearch),
    path('webtest_report/', webviews.webtest_report),
    path('apitest_report/', views.apitest_report),
    path('apptest_report/', appviews.apptest_report),
    path('test_report/', views.test_report),
    path('set_manage/', setviews.set_manage),
    path ('setsearch/', setviews.setsearch),
    path ('usersearch/', setviews.usersearch),
    path('user/', setviews.set_user),
    path('bug_manage/', bugviews.bug_manage),
    path ('bugsearch/', bugviews.bugsearch),
    path('cmdcase_manage/', cmdviews.cmdcase_manage),
    path('cmdcasestep_manage/', cmdviews.cmdcasestep_manage,name='cmdcasestep_manage'),
    path('cmdsearch/', cmdviews.cmdsearch),
    path('cmdstepsearch/', cmdviews.cmdstepsearch),
    path('cmdtest_report/', cmdviews.cmdtest_report),

]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cmdtest/models.py
from django.db import models

# Create your models here.

class Cmdcase(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)        # 关联产品id
    cmdcasename = models.CharField('用例名称',max_length=200)       # 测试用例名称
    cmdtestresult = models.BooleanField('测试结果')                 # 测试结果
    cmdtester = models.CharField('测试负责人',max_length=16)        # 执行人
    create_time = models.DateTimeField('创建时间',auto_now=True)    # 创建时间-自动获取当前时间
    class Meta:
        verbose_name = 'cmd测试用例'
        verbose_name_plural = 'cmd测试用例'
    def __str__(self):
        return self.cmdcasename

class Cmdcasestep(models.Model):
    Cmdcase = models.ForeignKey('Cmdcase',on_delete=models.CASCADE)    # 关联接口id
    cmdteststep = models.CharField('测试步聚',max_length=200)        # 测试步聚
    cmdtestobjname = models.CharField('cmd命令',max_length=200) # 测试对象名称描述
    assertdeclare = models.CharField('断言种类',max_length=200)      # 定位方式
    assertInfo1 = models.CharField('断言命令1',max_length=200)       # 控件元素
    assertInfo2 = models.CharField('断言命令2',max_length=200,null=True,blank=True)       # 操作方法
    assertInfo3 = models.CharField('断言命令3',max_length=200,null=True,blank=True)
    assertInfo4 = models.CharField('断言命令4',max_length=200,null=True,blank=True)
    cmdtestdata = models.CharField('测试数据',max_length=200,null=True,blank=True)   # 验证数据
    cmdtestresult = models.BooleanField('测试结果')                  # 测试结果
    create_time = models.DateTimeField('创建时间',auto_now=True)     # 创建时间-自动获取当前时间

    def __str__(self):
        return self.cmdteststep

cmdtest/templates/cmdcase_manage.html
<html lang="zh-CN">

 <head>
 {% load bootstrap4 %}
 {% bootstrap_css %}
 {% bootstrap_javascript %}
 <title>产品自动化测试管理平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />

 </head>
 <body role="document">
 <!-- 导航栏-->
 <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
 <div class="container">
<li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li> 
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
 <ul class="nav justify-content-center">  

</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
 </div>
 </nav>

<!-- 搜索栏-->
<div class="page-header" style="padding-top: 0px;">
<form class="navbar-form" method="get" action="/cmdsearch/">
 
{% csrf_token %}     
<input type="search" name="cmdcasename" placeholder="名称" required>
  
<button type="submit">搜索</button>
  
<!-- 增加cmd测试用例-->
<div style="float:right;width:65%">

<select name="Cmdcase" id="id_Cmdcase">
<option value="" selected>----cmd测试用例----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Cmdcase" data-href-template="/admin/cmdtest/cmdcase/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Cmdcase" href="/admin/cmdtest/cmdcase/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>  
</form>
</div>

 <!-- cmd测试用例列表-->
 <div class="row" style="padding-top: 20px;">
 <div class="col-md-12">
 <table class="table table-striped">
 <thead>
 <tr>
 <th>ID</th><th>产品</th><th>用例名称</th><th>结果</th><th>负责人</th><th>时间</th><th>操作</th><th>查看</th><th>编辑</th><th>删除</th>
 </tr>
 </thead>
 <tbody>
 {% for cmdcase in cmdcases %}
 <tr>
 <td>{{ cmdcase.id }}</td>
 <td>{{ cmdcase.Product.productname }}</td>
 <td>{{ cmdcase.cmdcasename }}</td>
 <td>{{ cmdcase.cmdtestresult }}</td>
 <td>{{ cmdcase.cmdtester }}</td>
 <td>{{ cmdcase.create_time }}</td>
     <td><button onclick="location.href='../task_cmdtest/?cmdcase.id={{ cmdcase.id }}',alert('开始运行')"  class="btn btn-primary">运行</button></td>
<td><a href="{% url "cmdcasestep_manage" %}?cmdcase.id={{ cmdcase.id }} "><img src="/static/admin/img/icon-yes.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Cmdcase" href="../admin/cmdtest/cmdcase/{{ cmdcase.id  }}/change/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-changelink.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Cmdcase" href="../admin/cmdtest/cmdcase/{{ cmdcase.id  }}/delete/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-deletelink.svg"/></a></td>
 </tr>
 {% endfor %}
 </tbody>
 </table>
 </div>
 </div>
<script>


function run_button(obj) {
        alert("开始执行...");
        var plan_id = obj.parentNode.parentNode.children[0].innerText;
        $.ajax({
            type: "post",
            url: "href="../task_cmdtest/",
            data: {"cmdcase.id": cmdcase.id},
            success: function (data) {
                alert(data);
            },
            error: function () {
                alert("执行失败");
            }
        });

    }

</script>

<!--统计和翻页功能-->
<span style="position:absolute; left:600px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:950px; bottom:25px; width:100px;">
共:{{ cmdcasecounts }}条记录 {# 前端读取定义的变量#}
</div>
<div class="container">
    <ul class="pagination" id="pager">
          {# 上一页链接开始#}
        {% if cmdcases.has_previous %}
            {#  如果有上一页则正常显示上一页链接#}
            <li class="previous"><a href="/cmdcase_manage/?page={{ cmdcases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
        {% endif %}
        {# 上一页链接开始#}
        
        {% for num in cmdcases.paginator.page_range %}
         
            {% if num == currentPage %}
                <li class="item active"><a href="/cmdcase_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#}
            {% else %}
                <li class="item"><a href="/cmdcase_manage/?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        
        {# 下一页链接开始#}
        {% if cmdcases.has_next %} {#  如果有下一页则正常显示下一页链接#}
            <li class="next"><a href="/cmdcase_manage/?page={{ cmdcases.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页链接结束#}
    </ul>
</div>

 </body>
 </html>
 

cmdtest/templates/cmdcasestep_manage.html
<html lang="zh-CN">

 <head>
 {% load bootstrap4 %}
 {% bootstrap_css %}
 {% bootstrap_javascript %}
 <title>产品自动化测试平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />

<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>




    
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    


<meta name="robots" content="NONE,NOARCHIVE" />
<style>
body{text-align:center;overflow:hidden;text-overflow:ellipsis}
.divcss5-a,.divcss5-b{ width:auto; height:945px; float:left;}
.divcss5-b{ margin-left:0px;overflow-x:hidden;overflow-y:scroll;}
 </style>
 </head>
 <body role="document">
 <!-- 导航栏-->
 <div class="divcss5-a">
     <div class="divcss5-b">
 <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
 <div class="container">
<li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
 </div>
 </nav>

 <!-- 用例步聚列表-->
 <div class="row" style="padding-top: 0px;" >
 <div class="col-md-12">

  <style>

td {white-space:nowrap;overflow:hidden;text-overflow: ellipsis; }


</style>
 <table class="table table-striped" style="table-layout: fixed;overflow-y:scroll">
 <thead>

 <tr> 
 <th>产品</th><th>所属用例</th><th>步聚</th><th>断言类型</th><th>断言信息1</th><th>断言信息2</th><th>断言信息3</th><th>断言信息4</th><th>测试结果</th><th>时间</th>
 </tr>
 </thead>
 <tbody>
    <div class="scroll-container">
          <div class="scroll-content"></div>
      </div>
 {% for cmdcasestep in cmdcasesteps %}
 <tr>
{% if cmdcasestep.Cmdcase.id == cmdcase.id  %}
 <td>{{ cmdcasestep.Cmdcase.Product.productname }} </td>
 <td>case_{{ cmdcasestep.Cmdcase.id }}_{{ cmdcasestep.Cmdcase.cmdcasename }}</td>
 <td >{{ cmdcasestep.cmdteststep }}:{{ cmdcasestep.cmdtestobjname }}</td>
 <td>{{ cmdcasestep.assertdeclare }}</td>
 <td>{{ cmdcasestep.assertInfo1 }}</td>
 <td>{{ cmdcasestep.assertInfo2 }}</td>
 <td>{{ cmdcasestep.assertInfo3 }}</td>
  <td>{{ cmdcasestep.assertInfo4 }}</td>
<!--  <td>{{ cmdcasestep.cmdtestdata }}</td>-->
   {% if cmdcasestep.cmdtestresult == 'FAIL' %}</td>
   <td><font size="3" color="red">{{ cmdcasestep.cmdtestresult }}</font></td>
   {% elif cmdcasestep.cmdtestresult == 'PASS' %}
   <td><font size="3" color="green">{{ cmdcasestep.cmdtestresult }}</font></td>
   {% else %}
   <td><font size="3" color="black">{{ cmdcasestep.cmdtestresult }}</font></td>
   {% endif %}
 <td>{{ cmdcasestep.create_time }}</td>
{% else %}
{% endif %}
 </tr>
 {% endfor %}
 </tbody>
 </table>
 </div>
 </div>
</div>
 </div>




<td>
<a style='color:light blue'  href="../cmdcase_manage/" >
<img src="/static/admin/img/icon-yes.svg" alt="返回"/>返回
</a>
</td>

<td>
<a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Cmdtest" href="../admin/cmdtest/cmdcase/{{ cmdcase.id  }}/change/?_to_field=id&_popup=1">
<img src="/static/admin/img/icon-changelink.svg"/>编辑</a>
</td>
 </body>
 </html>

cmdtest/templates/cmdtestreport.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试管理平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">

<li class="active"><a style='color:white' href="/test_report/">单一接口</a></li> 
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apitest_report/">流程接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apptest_report/">app报告</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/webtest_report/">web报告</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<ul class="nav justify-content-center">  
</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>
<div class="row" style="padding-top: 0px;">
<div class="col-md-12">

<table class="table table-striped">
<div style="position:absolute;  right:10px; width:10px; ">
<tr><th>自动化测试报告-Linux测试<td>{{ cmdcase.create_time }}</td><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th></th></tr>
<tr><th>用例总数</th> <td>{{ cmdscounts }}</td></td></td></td></tr> {# 前端读取定义的变量#}
<tr><th>通过</th><td>{{ cmds_pass_counts }}</td><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th></tr>
<tr><th>不通过</th><td><a style='color:red'>{{ cmds_fail_counts }}</a> </td><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th></tr>

</div>

</table>


<!-- 单一接口测试用例-->
<table class="table table-striped" style="table-layout: fixed;">
<style>
td {
      white-space:nowrap;overflow:hidden;text-overflow: ellipsis;
}
</style>

<thead>

<tr><th>不通过详情</th><td>
<tr>
<th>产品</th><th>用例名称</th><th>测试步骤</th><th>执行时间</th>
</tr>
</thead>
<tbody>
 {% for cmdcasestep in cmds %}
<tr>
{% if cmdcasestep.cmdtestresult == 'FAIL' %}

 <td>{{ cmdcasestep.Cmdcase.Product.productname }}</td>
 <td>{{ cmdcasestep.Cmdcase.cmdcasename }}</td>
 <td>{{ cmdcasestep.cmdtestobjname }}</td>
<!-- <td>{{ cmdcasestep.cmdtestresult }}</td>-->
 <td>{{ cmdcasestep.create_time }}</td>
{% else %}
{% endif %}
</tr>
{% endfor %}
</tbody>
</table>

</div>
</div>


</body>
</html>